name: stubudmvp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  swipeable_button_view: ^0.0.2
  page_transition: ^2.0.5
  image_picker: ^1.1.2
  awesome_dialog: ^3.2.1
  sqflite: ^2.4.1
  path: ^1.8.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  firebase_messaging: ^15.1.6
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/imad/image.png
    - images/imad/photo_2024-10-06_12-41-09.jpg
    - images/feriel/image.png
    - images/feriel/image2.png
    - images/billel/image.png
    - images/billel/image2.png
    - images/billel/image3.png
    - images/rayane/rayane.png
    - images/rayane/rayane1.png
    - images/badri/badri.jpg
